#!/usr/bin/env bash
# brain-lint.sh — 週次lint（exbrain 2.0）。LLM不使用の決定論チェック。
# launchd: com.YOURNAME.brain-lint（毎週日曜09:00）。旧 weekly-sync.sh の後継。
# 検出: 壊れwikilink / iCloud競合コピー / byte-identical重複 / 陳腐化 / 期限切れresearch / daily欠落 / frontmatter欠落
set +e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/lib/platform.sh"
VAULT="$HOME/vault"
REPORT="$VAULT/system/lint-report.md"
cd "$VAULT" 2>/dev/null || exit 0

python3 - "$VAULT" > "$REPORT" 2>/dev/null <<'PYEOF'
import os, re, sys, json, filecmp, datetime
vault = sys.argv[1]
today = datetime.date.today()
issues = {"broken_links": [], "conflict_copies": [], "dupes": [], "stale": [], "expired": [], "missing_daily": [], "no_frontmatter": []}

SKIP_DIRS = {'.git', '.obsidian', 'templates'}
mds, all_names = [], set()
for root, dirs, files in os.walk(vault):
    dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
    for f in files:
        p = os.path.join(root, f)
        rel = os.path.relpath(p, vault)
        if re.search(r' \d\.(md|sh|json|lock)$', f):
            issues["conflict_copies"].append(rel)
            base = os.path.join(root, re.sub(r' \d(\.[^.]+)$', r'\1', f))
            if os.path.exists(base) and filecmp.cmp(p, base, shallow=False):
                issues["dupes"].append(rel)
        if f.endswith('.md'):
            mds.append(rel)
            all_names.add(rel[:-3]); all_names.add(os.path.splitext(f)[0])

for rel in mds:
    p = os.path.join(vault, rel)
    try: txt = open(p, encoding='utf-8', errors='ignore').read()
    except Exception: continue
    top = rel.split('/')[0]
    # 壊れwikilink（wiki層のみ検査。daily/clipsの過去リンクは触らない）
    # スキーマ/ナビファイルは例示リンクを含むため除外
    if rel not in ('CLAUDE.md', 'INDEX.md') and (top in ('entities', 'clients', 'insights', 'research', 'decisions') or '/' not in rel):
        scan = re.sub(r'`[^`]*`', '', txt)  # インラインコード（書式例）内のリンクは除外
        for m in re.finditer(r'\[\[([^\]|#\\]+)', scan):  # \\ を除外して alias `\|` を正しく分離
            t = m.group(1).strip().rstrip('/').removesuffix('.md')
            if not t or t.startswith(('http', '#')): continue
            if re.search(r'YYYY|MM-DD|フォルダ|ファイル名|<|>', t): continue  # 例示プレースホルダ
            if t not in all_names and not os.path.exists(os.path.join(vault, t + '.md')):
                issues["broken_links"].append(f"{rel} → [[{t}]]")
    # frontmatter（wiki層のみ必須）
    if top in ('entities', 'clients', 'insights', 'research', 'decisions') and not txt.startswith('---'):
        issues["no_frontmatter"].append(rel)
    # research期限切れ
    if top == 'research':
        m = re.search(r'^expires:\s*(\d{4}-\d{2}-\d{2})', txt, re.M)
        if m and datetime.date.fromisoformat(m.group(1)) < today:
            issues["expired"].append(f"{rel} (expires {m.group(1)})")
    # system/ミラー陳腐化（45日超）
    if top == 'system' and rel.endswith('.md'):
        m = re.search(r'^updated:\s*(\d{4}-\d{2}-\d{2})', txt, re.M)
        if m and (today - datetime.date.fromisoformat(m.group(1))).days > 45:
            issues["stale"].append(f"{rel} (updated {m.group(1)})")

# daily欠落（直近7日）
for i in range(1, 8):
    d = today - datetime.timedelta(days=i)
    f = os.path.join(vault, 'daily', f'{d}.md')
    if not os.path.exists(f):
        issues["missing_daily"].append(str(d))
    elif os.path.getsize(f) < 200:
        issues["missing_daily"].append(f"{d}（{os.path.getsize(f)}B・ほぼ空）")

# wiki鮮度: clients/entitiesで30日以上更新なし かつ 直近7日のdailyに名前が出るもの
recent_txt = ""
for i in range(0, 8):
    f = os.path.join(vault, 'daily', f'{today - datetime.timedelta(days=i)}.md')
    if os.path.exists(f): recent_txt += open(f, encoding='utf-8', errors='ignore').read()
for sub in ('clients', 'entities'):
    for root, dirs, files in os.walk(os.path.join(vault, sub)):
        for f in files:
            if not f.endswith('.md') or f.startswith('_'): continue
            p = os.path.join(root, f)
            age = (today - datetime.date.fromtimestamp(os.path.getmtime(p))).days
            name = os.path.splitext(f)[0]
            if age > 30 and name in recent_txt:
                issues["stale"].append(f"{os.path.relpath(p, vault)}（{age}日前・直近dailyに言及あり）")

total = sum(len(v) for v in issues.values())
sev = "🟢 clean" if total == 0 else ("🟡 %d issues" % total if not issues["broken_links"] and not issues["conflict_copies"] else "🔴 %d issues" % total)
print(f"<!-- auto-generated by brain-lint.sh — DO NOT EDIT -->")
print(f"# Lint Report — {today} — {sev}\n")
labels = {"broken_links":"壊れたwikilink（wiki層）","conflict_copies":"iCloud競合コピー","dupes":"うちbyte-identical（削除可）","stale":"陳腐化","expired":"期限切れresearch","missing_daily":"daily欠落/空","no_frontmatter":"frontmatter欠落"}
for k, label in labels.items():
    v = issues[k]
    print(f"## {label}: {len(v)}件")
    for x in v[:20]: print(f"- {x}")
    if len(v) > 20: print(f"- ...他{len(v)-20}件")
    print()
json.dump({"date": str(today), "total": total, "counts": {k: len(v) for k, v in issues.items()}},
          open(os.path.join(vault, 'system', '.lint-latest.json'), 'w'))
PYEOF

# RED（壊れリンク・競合コピーあり）ならローカル通知
total=$(python3 -c "import json;d=json.load(open('$VAULT/system/.lint-latest.json'));print(d['counts']['broken_links']+d['counts']['conflict_copies'])" 2>/dev/null || echo 0)
[ "${total:-0}" -gt 0 ] && notify "exbrain lint 🔴" "lint: 要対応 ${total}件（system/lint-report.md）"

# コミット（レポートのみ）
if [ -n "$(git status --porcelain -- system/ 2>/dev/null)" ]; then
  git add system/ && git commit -q -m "lint: weekly report $(date +%F)"
fi
exit 0
